name: moments
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #ui
  introduction_screen: 3.1.8
  cupertino_icons: 1.0.5
  figma_squircle: 0.5.3
  google_fonts: 4.0.4
  flutter_svg: 2.0.6
  equatable: 2.0.5
  flutter_gen: 5.3.1
  scroll_snap_list: 0.9.1
  cached_video_player: ^2.0.4
  lottie: ^2.3.2

  #system
  flutter_local_notifications: 11.0.1
  permission_handler: 10.2.0
  path_provider: 2.0.15
  file_picker: 5.2.0+1
  get_it: 7.6.0
  intl: 0.18.1
  fast_i18n: ^5.11.0

  #data
  shared_preferences: 2.1.1
  sqflite: 2.2.8+4
  json_serializable: 6.7.0
  dio: 5.1.2
  pretty_dio_logger: 1.3.1
  pocketbase: 0.10.0

  #state
  flutter_bloc: 8.1.3
  provider: 6.0.5

dev_dependencies:
  flutter_gen_runner: 5.3.1
  build_runner: 2.2.1

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/
    - assets/animation/
    - lib/i18n/
